# Generated by Django 4.2 on 2025-05-04 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('PRODUCT_POST', 'Product Post'), ('REVIEW', 'Review/Rating'), ('QUESTION', 'Question'), ('ANSWER', 'Answer')], max_length=20)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(blank=True, help_text='Rating out of 5 (for reviews only)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='For answers to questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app1.communitypost')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='app1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
