# Generated by Django 4.2 on 2025-05-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
