# Generated by Django 4.2 on 2025-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_add_default_community_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
    ]
