# Generated by Django 4.2 on 2025-05-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_communitycategory_options_review_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
