# Generated by Django 4.2 on 2025-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_cleanup_and_add_community_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
