# Generated by Django 4.2 on 2025-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
