FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY requirements_django.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements_django.txt

COPY . /usr/src/app/

RUN chmod +x /usr/src/app/entrypoint.sh

EXPOSE 8000

CMD ["/usr/src/app/entrypoint.sh"]